Translate README.md to Latin
Pissandshittium/pissandshittium pull request #17
Opened 2023-12-17 21:41 UTC by qwool

if anyone wants to edate please reply in this thread i am gay

2023-12-17 21:47 UTC, Susmaster64 requested changes
change into enchanting table language + latin?

2023-12-17 21:50 UTC, yotoprules approved these changes

2023-12-18 03:32 UTC, Alliegaytor requested changes
UsInG AlTeRnAtInG CaPs wOuLd mAkE ThIs mOrE ReAdAbLe. I Do aGrEe wItH ThE PrEmIsE Of tHiS Pr aNd aM AwAiTiNg iTs mErGe

2023-12-18 06:48 UTC, Aikoyori commented
we need Enchanting table script

2023-12-18 08:00 UTC, armchairpsycho1 commented
> we need Enchanting table script

Getting someone who knows Georgian in on this for you, he might be able to help

2023-12-18 08:15 UTC, neebooo commented
We should translate to ancient Hungarian instead or translate half of it to Latin and half of it to ancient Hungarian. Promoting equality!

2023-12-18 21:43 UTC, Susmaster64 commented
I agree with neebooo, we need to promote equality. So I think that every word has to be from a different language on the readme!

2024-01-04 07:49 UTC, nail-e commented
I second with neebooo, but I suggest that each new word should be in a different unicode glyph

2025-03-22 11:57 UTC, closed without merging